/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './index.tsx', './App.tsx', './components/**/*.{ts,tsx}', './screens/**/*.{ts,tsx}', './data/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Oswald', 'sans-serif'],
        hud: ['"Chakra Petch"', 'monospace'],
      },
      colors: {
        carbon: '#0A0B0C',
        carbon2: '#0D0E10',
        surface: '#141619',
        surface2: '#1A1D21',
        edge: 'rgba(255,255,255,0.07)',
        accent: '#CAD2DA',
        accent2: '#9AA3AD',
        ember: '#FF6A2C',
        cyan: '#38E1F0',
        blue: '#2C90FF',
        danger: '#FF3B30',
        good: '#37E29A',
        muted: '#7C828A',
        ghost: '#F4F5F6',
        // legacy tokens (kept so nothing referencing old names breaks) — carbon-mapped
        ink: '#0A0B0C',
        panel: '#141619',
        panel2: '#1A1D21',
        hud: '#CAD2DA',
        bg: '#0A0B0C',
        darkBg: '#0A0B0C',
        textMain: '#F4F5F6',
        textMuted: '#7C828A',
      },
      boxShadow: {
        card: '0 20px 50px -18px rgba(0,0,0,0.85)',
        glow: '0 0 24px rgba(255,255,255,0.22)',
        edge: 'inset 0 1px 0 rgba(255,255,255,0.06)',
      },
      borderRadius: { xl2: '1.25rem', xl3: '1.75rem' },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'rise': 'rise 0.55s cubic-bezier(0.16,1,0.3,1) both',
        'fade': 'fade 0.4s ease both',
        'slow-zoom': 'slowZoom 22s linear infinite alternate',
        'spin-slow': 'spin 16s linear infinite',
        'grid-pan': 'gridPan 24s linear infinite',
        'sheen': 'sheen 3.5s ease-in-out infinite',
        'scan': 'scan 3.2s linear infinite',
        'pulse-dot': 'pulseDot 2s ease-in-out infinite',
        'boot-bar': 'bootBar 1s cubic-bezier(0.5,0,0.2,1) forwards',
      },
      keyframes: {
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        rise: { '0%': { opacity: 0, transform: 'translateY(18px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        fade: { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        slowZoom: { '0%': { transform: 'scale(1)' }, '100%': { transform: 'scale(1.14)' } },
        gridPan: { '0%': { backgroundPosition: '0 0' }, '100%': { backgroundPosition: '44px 44px' } },
        sheen: { '0%,100%': { opacity: 0.0 }, '50%': { opacity: 0.5 } },
        scan: { '0%': { transform: 'translateY(-120%)' }, '100%': { transform: 'translateY(420%)' } },
        pulseDot: { '0%,100%': { opacity: 1, transform: 'scale(1)' }, '50%': { opacity: 0.4, transform: 'scale(0.7)' } },
        bootBar: { '0%': { width: '0%' }, '100%': { width: '100%' } },
      },
    },
  },
  plugins: [],
};
