/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './index.tsx', './App.tsx', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Oswald', 'sans-serif'],
        hud: ['"Chakra Petch"', 'monospace'],
      },
      colors: {
        ink: '#08090B',
        panel: '#0E1114',
        panel2: '#14181C',
        steel: '#1B2026',
        line: 'rgba(255,255,255,0.08)',
        hud: '#38E1F0',
        hud2: '#2C90FF',
        ember: '#FF6A2C',
        danger: '#FF3B30',
        epic: '#8A6BFF',
        muted: '#8A9099',
        // legacy tokens (dark-locked) kept for safety
        bg: '#08090B',
        darkBg: '#08090B',
        surface: '#0E1114',
        surface2: '#14181C',
        darkSurface: '#14181C',
        textMain: '#FFFFFF',
        darkTextMain: '#FFFFFF',
        textMuted: '#8A9099',
        darkTextMuted: '#8A9099',
      },
      boxShadow: {
        hud: '0 0 0 1px rgba(56,225,240,0.35), 0 0 24px rgba(56,225,240,0.18)',
        panel: '0 18px 50px -12px rgba(0,0,0,0.8)',
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'float-up': 'floatUp 0.5s cubic-bezier(0.16,1,0.3,1) both',
        'fade-in-up': 'fadeInUp 0.8s cubic-bezier(0.16,1,0.3,1) both',
        'slow-zoom': 'slowZoom 20s linear infinite alternate',
        'spin-slow': 'spin 14s linear infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4,0,0.6,1) infinite',
        'grid-pan': 'gridPan 22s linear infinite',
        sheen: 'sheen 3.2s linear infinite',
        flicker: 'flicker 4s linear infinite',
        sway: 'sway 7s ease-in-out infinite',
        'scan-loop': 'scanLoop 4s linear infinite',
      },
      keyframes: {
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        floatUp: { '0%': { opacity: 0, transform: 'translateY(14px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        fadeInUp: { '0%': { opacity: 0, transform: 'translateY(24px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        slowZoom: { '0%': { transform: 'scale(1)' }, '100%': { transform: 'scale(1.12)' } },
        gridPan: { '0%': { backgroundPosition: '0 0' }, '100%': { backgroundPosition: '40px 40px' } },
        sheen: { '0%': { transform: 'translateX(-120%) skewX(-20deg)' }, '60%,100%': { transform: 'translateX(220%) skewX(-20deg)' } },
        flicker: { '0%,100%': { opacity: 1 }, '92%': { opacity: 1 }, '94%': { opacity: 0.55 }, '96%': { opacity: 1 } },
        sway: { '0%,100%': { transform: 'rotateY(-6deg)' }, '50%': { transform: 'rotateY(6deg)' } },
        scanLoop: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(400%)' } },
      },
    },
  },
  plugins: [],
};
